function Options(){
	var place = $(".selector.place-number");
	var color = $(".selector.color-number");
	var reset = $(".options .reset");
	var giveup = $(".options .giveup");
	var instructions = $(".options .instructions");
	
	var onSelect = function(){};
	var onReset = function(){};
	var onGiveUp = function(){};

	reset.click(function(){onReset();});
	giveup.click(function(){onGiveUp();});
	instructions.click(function(){onShowInstructions();})
	
	function onShowInstructions(){
		var msg = "This is a version of popular Mastermind game. Code is randomly generated by the computer. The code consists of 3-6 colors and each color can exist more then once within the hidden code. <br><br> You play the game starting at the bottom until you fill all row code pegs. You choose the guess colour by mouse clicking on the each code peg position. After creating your guess row, you click 'Check' button.<br><br>After you click 'Check', black and white key pegs will appear on the right. The black key peg indicates that one of your code pegs is on the right position and with right colour. White key peg indicates that one of your code pegs is right colour in the wrong position.<br><br> You need to guess hidden code in minimum number of tries.";
	
		$('.dialogCover').show();
		$('.dialog').addClass("how-to-play").show().empty().append(msg).append($('<button/>', { 
			html: 'Close',
			click: function(){
				$('.dialog').hide();
				$('.dialogCover').hide();
			}
		}));
	}
	
	return{
		get colorNumber() {return color.val()},
		get placeNumber() {return place.val()},
		setOnStart: function(handler){
			onReset = handler;
		},
		setOnGiveUp: function(handler){
			onGiveUp = handler;
		}
	};
}